const data_electricity_supplier_name = {
  ALTI: "GB Energy Supply Limited",
  ANGE: "Limejump Energy Limited",
  AVRO: "AVRO ENERGY LIMITED",
  AXIS: "Axis Telecom Limited",
  AXPO: "Axpo UK Limited",
  AZAC: "Azacca Energy Limited",
  BARB: "Barbican Power Limited",
  BAYS: "Bayswater Energy Limited",
  BCFC: "GEN4U Limited",
  BETH: "Mongoose Energy Supply Limited",
  BGAS: "British Gas Trading Ltd",
  BIZZ: "British Gas Trading Ltd",
  BLBL: "Bluebell Energy Supply Ltd",
  BNRG: "Electricity Plus Supply Ltd",
  BORE: "Bor Energy Limited",
  BREZ: "Breeze Energy Supply Limited",
  BRZE: "arto.energy Limited",
  BULN: "Bullion Energy Limited",
  CALL: "Extra Energy Supply Limited",
  CFWR: "Cornflower Energy Supply Ltd",
  CIRC: "Flow Energy Ltd",
  CNDL: "NEAS Energy Limited",
  CNRG: "Opus Energy (Corporate) Ltd.",
  COMT: "Comet Energy Limited",
  COOP: "I Supply Energy Limited",
  CORE: "Corona Energy Retail 4 Limited",
  COUL: "Coulomb Energy Supply Limited",
  COVE: "Covent Energy Limited",
  CPPR: "Affect Energy Ltd",
  CYCL: "Business Power and Gas Limited",
  DESL: "Daisy Energy Supply Limited",
  DFDL: "Daffodil Energy Supply Ltd",
  DNRG: "Donnington Energy Limited",
  DUAL: "Dual Energy Direct Limited",
  EBES: "BES Commercial Electricity Ltd",
  ECOA: "British Gas Trading Ltd",
  ECON: "Reuben Power Supply Limited",
  ECOT: "Renewable Energy Company Ltd",
  EDGE: "EDGWARE ENERGY LIMITED",
  EDIR: "Electricity Direct (UK)",
  EELC: "E.ON Energy Ltd",
  EENG: "E.ON Energy Ltd",
  EESL: "ECONOMY ENERGY SUPPLY LTD",
  EETL: "Economy Energy Trading Limited",
  EFLS: "Effortless Energy Ltd",
  EGML: "ECO GREEN MANAGEMENT LIMITED",
  ELEC: "ELECTRAPHASE LIMITED",
  EMEB: "E.ON Energy Ltd",
  ENDC: "EPG Energy Ltd",
  ENEC: "Eneco Energy Trade B.V.",
  ENGQ: "Eversmart Energy Ltd",
  ENRD: "British Gas Trading Ltd",
  ENRG: "Opus Energy Renewables Limited",
  EPHH: "Trafford Plaza",
  ESSL: "Energy Supply Solutions Ltd",
  EURO: "Robin Hood Energy Limited",
  FARR: "FARRINGDON ENERGY LIMITED",
  FNRG: "Farmoor Energy Limited",
  FRST: "First Utility Ltd",
  FSEN: "F & S Energy Ltd.",
  FXGL: "Foxglove Energy Supply Limited",
  GALE: "Galena Energy Limited",
  GANY: "LOCO2 Energy Supply Limited",
  GESL: "SO Energy Trading Limited",
  GETW: "Utilita Energy Limited",
  GMTR: "Gazprom Marketing & Trading Retail Ltd",
  GNRG: "Green Energy UK Plc",
  GONG: "Golding Energy Limited",
  HAVE: "Haven Power Limited",
  HOLB: "Holborn Energy Limited",
  HOME: "ENGIE Power Limited",
  HPOW: "Haven Power Limited",
  HUDS: "Hudson Energy Supply UK Ltd",
  HYDE: "SSE Plc",
  IMPO: "SSE Plc",
  INDE: "NPOWER DIRECT LTD NHH",
  INVE: "INVERNO LIMITED",
  IRES: "Iresa Limited",
  IRID: "PfP Energy Supplies Ltd",
  JERE: "Hudson Energy Supply UK Ltd",
  KENS: "Kensington Power Limited",
  LIGH: "MVV Environment Services Limited",
  LILY: "Lily Energy Supply Ltd",
  LOND: "EDF Energy",
  LORM: "E (GAS AND ELECTRICITY) LTD",
  LUME: "GNERGY Limited",
  LVDR: "Lavender Energy Supply Limited",
  MAEL: "MA Energy Ltd",
  MAET: "MA Energy Ltd",
  MAGN: "DONG Energy Power Sales UK Ltd",
  MANW: "Scottish Power Energy Retail Ltd",
  MARB: "Marble Power Limited",
  MARI: "Marigold Energy Supply Limited",
  MATT: "MATTINA LIMITED",
  MIDE: "NPOWER LTD",
  MINT: "Mint Energy Supply Limited",
  MRCY: "Octopus Energy Limited",
  MTRL: "Brook Green Trading Limited",
  NATP: "Npower Ltd",
  NCKL: "Brilliant Energy Supply Limited",
  NEEB: "npower Northern Limited",
  NEWP: "Newport Energy Limited",
  NORW: "E.ON Energy Ltd",
  NUCE: "Nuclear Decommissioning Authority Ltd",
  OBER: "Addito Supply Limited",
  OGAS: "British Gas Trading Ltd",
  OPAL: "Opal Energy Limited",
  OSMI: "BRISTOL ENERGY",
  OVOE: "OVO Energy",
  OXPO: "Opus Energy Limited",
  PADD: "Paddington Power Limited",
  PALL: "Palladium Energy Supply Limited",
  PGEN: "EON Energy Solutions Limited",
  PILO: "Tonik Energy Limited",
  PION: "Pioneer Energy Limited",
  POWQ: "Hartree Partners Supply (UK) Limited",
  PROZ: "PROZANA LIMITED",
  PSUK: "Npower Ltd",
  PURE: "Good Energy Limited",
  REGE: "Bulb Energy Ltd",
  RENC: "The Renewable Energy Company Ltd",
  RHOD: "Our Power Energy Supply Ltd",
  ROSE: "Rose Energy Supply Ltd",
  RWED: "GDF SUEZ Marketing Ltd",
  SANT: "Santiam Energy Limited",
  SEEB: "EDF Energy",
  SING: "SINGOLA LIMITED",
  SINQ: "SINQ POWER LIMITED",
  SIRO: "Future Energy Utilities Limited",
  SLVR: "CNG Electricity Limited",
  SMAR: "SmartestEnergy Limited",
  SNFR: "Sunflower Energy Supply Ltd",
  SOUT: "SSE Plc",
  SPOW: "Scottish Power Energy Retail Ltd",
  SPRK: "Spark Energy Supply Ltd",
  STAT: "Statkraft Markets GmbH",
  SWAE: "SSE Plc",
  SWDP: "Snowdrop Energy Supply Limited",
  SWEB: "EDF Energy",
  SYMB: "SYMBIO ENERGY LTD",
  TEAM: "The Team Group of Companies UK Limited",
  TGPL: "Total Gas and Power Ltd",
  THLE: "Thistle Energy Supply Ltd",
  THRE: "Corona Energy Retail 4 Limited",
  TLWD: "Bruntwood Energy Services Ltd",
  TNDO: "Pozitive Energy Limited",
  TRAM: "Switch Business Gas & Power",
  TREX: "Power4All Limited",
  TULP: "Tulip Energy Supply Limited",
  UKPR: "UK POWER RESERVE LIMITED",
  VAVU: "Vavu Power Limited",
  VETS: "Vattenfall Energy Trading GmbH",
  VOLT: "The Co-operative Energy Ltd",
  YELG: "NPOWER YORKSHIRE SUPPLY LTD",
  ZPYR: "Green Network Energy Ltd",
  IDK: "I don’t know my supplier"
}

export default data_electricity_supplier_name;