const data_gas_supplier_name = {
    OBR: "Addito Supply Limited",
    AFG: "Affect Energy Limited",
    AMP: "Ampoweruk Ltd",
    AVA: "Avantigas On Ltd",
    OEL: "Avid Energy Limited",
    AVR: "Avro Energy Limited",
    AXI: "Axis Telecom",
    EUK: "Axpo UK Limited",
    BSH: "Barrow Shipping Limited",
    BTS: "Better Energy Supply Ltd",
    BLU: "Bluegreen Energy Services Limited",
    BPL: "BP Gas Marketing Limited",
    BZE: "Breeze Energy Supply Limited",
    BSD: "Brits Energy Limited",
    BPW: "Brighton Power Limited",
    BEY: "Brilliant Energy Supply Limited",
    BNT: "Bristol Energy Limited",
    BGB: "British Gas Business",
    BGT: "British Gas Trading Limited",
    BSA: "British Gas Trading Ltd (2nd)",
    BRO: "Brook Green Trading LTD",
    BUN: "Bruntwood Energy Services Limited",
    HBL: "Bulb Energy Limited",
    BEN: "Business Energy Solutions Limited",
    BPO: "Business Power & Gas",
    CAS: "Callesti Energy Supply Limited",
    TEN: "Ceres Energy Limited",
    CNT: "Contract Natural Gas Limited",
    COP: "Co-Operative Energy Limited",
    COO: "Co-Operative Energy Limited",
    QNT: "Corona Energy Retail 1 Limited",
    VCT: "Corona Energy Retail 2 Limited",
    SLG: "Corona Energy Retail 3 Limited",
    GLZ: "Corona Energy Retail 4 Limited",
    COU: "Coulomb Energy Supply Limited",
    CGP: "Crown Gas and Power Limited",
    CRW: "Crown Oil Limited",
    DRA: "Drax Power Limited",
    DSY: "Daisy Energy Supply Limited",
    DLG: "Daligas Ltd",
    DGP: "Delta Gas and Power Limited",
    DER: "Derwent Co Generation Ltd",
    DLE: "Dual Energy Direct Limited",
    DCE: "Dyce Energy Limited",
    LMR: "E (Gas & Electricity) Ltd",
    EGD: "E (Gas & Electricity) Ltd",
    OWN: "E.ON Energy Gas (Eastern) Limited",
    ATE: "E.ON Energy Gas (Northwest) Limited",
    EST: "E.ON Energy Solutions Limited",
    SGL: "E.ON Energy Solutions Limited",
    SGY: "E.ON Energy Solutions Limited",
    TUU: "E.ON Energy Solutions Limited",
    EOD: "E.ON Energy Solutions Limited",
    POW: "E.ON UK Plc",
    EES: "Eclipse Energy Supply Ltd",
    EGM: "Eco Green Management Limited",
    YGP: "Eco Green Management Ltd",
    ECO: "Economy Gas Limited",
    KIN: "Economy Power Limited",
    EDD: "Eddington Energy Supply Limited",
    LED: "EDF Energy Customers Limited",
    SBR: "EDF Energy Customers Limited",
    EDS: "EDF Energy Customers Limited",
    LDE: "EDF Trading Limited",
    LEI: "EDF Trading Limited",
    EEL: "Effortless Energy Ltd",
    VES: "Engie Gas Limited",
    RWT: "Engie Power Limited",
    ESA: "ENI Trading & Shipping SPA",
    AGP: "Eni UK Limited",
    ERO: "Enstroga Limited",
    ETI: "Entice Energy Supply Limited",
    EEC: "Entice Energy Supply Limited",
    TUK: "Eon Energy Solutions Limited",
    EAS: "E.ON Energy Gas (Eastern) Limited",
    PWR: "Eon UK Gas Limited",
    EMI: "Eon UK Industrial Shipping Limited",
    PWG: "Eon UK Plc",
    EPU: "EP UK Investments Ltd",
    STT: "Equinor Energy Trading Limited",
    STA: "Equinor UK Limited",
    EBE: "ESB Energy Limited",
    EED: "Euston Energy Limited",
    ENQ: "Eversmart Energy Ltd",
    EVR: "Eversmart Energy Ltd",
    EGE: "Exelon Generation Limited",
    XOM: "ExxonMobil Gas Marketing Europe Ltd",
    FDY: "Fidelity Energy Limited",
    FUZ: "SHELL ENERGY RETAIL LIMITED",
    FLE: "Flexitricity Limited",
    FGB: "Flogas Britain Limited",
    CES: "Flow Energy Ltd",
    FOX: "Foxglove Energy Supply Limited",
    FGP: "Fylde Utilities UK Limited",
    GAP: "Gas & Power Ltd",
    AEL: "Gas Plus Supply Limited",
    GMT: "Gazprom M&T Limited",
    VLN: "GDF Suez Energy (UK) Limited",
    GHL: "GnERGY Limited",
    GOE: "Go Effortless Ltd",
    GEG: "Good Energy Gas Limited",
    GTE: "GOTO Energy (UK) Limited",
    AMB: "Great Western Energy Ltd",
    GNL: "Green Energy (UK) plc",
    GSL: "Green Energy Supply Limited",
    GNE: "Green Network Energy Limited",
    HPR: "Hartlepower CIC",
    HEP: "Hess Energy Power & Gas Company UK Ltd",
    HBE: "Holborn Energy Limited",
    HET: "Home Energy Trading Ltd",
    HUD: "Hudson Energy Supply UK Limited",
    JER: "Hudson Energy Supply UK Ltd",
    ISE: "I Supply Energy Limited",
    IAZ: "I.A.Z.F.S Limited",
    ICD: "ICD Gas Limited",
    IGL: "Igloo Energy Supply Limited",
    IPO: "International Power Fuel Company Ltd",
    JPS: "JP Morgan Securities Limited",
    KEP: "Keep Energy Limited",
    KEL: "Kensington Power Limited",
    KNP: "Kensington Power Limited",
    MRB: "Marble Power Limited",
    MAC: "Macquarie Bank Ltd",
    MAT: "Mattina Limited",
    MAX: "Maxen Power Supply Limited",
    SEL: "Mercuria Energy Europe Trading Limited",
    MER: "Mercuria Energy Trading SA",
    MPE: "MoneyPlus Energy Limited",
    MOG: "Mongoose Energy Supply Limited",
    PSS: "N power Gas Ltd",
    SAN: "Nabuh Energy Limited",
    NSL: "North Sea Gas Ltd",
    NGD: "Npower Commercial Gas Limited",
    NPC: "Npower Commercial Gas Limited",
    NDS: "Npower Direct Limited",
    IND: "Npower Direct Ltd",
    CLT: "Npower Gas Limited",
    TCG: "Npower Gas Ltd",
    NRZ: "Npower Northern Limited",
    GUK: "Npower Northern Ltd",
    YGS: "Npower Yorkshire Limited",
    YKE: "Npower Yorkshire Ltd",
    OCT: "Octopus Energy Limited",
    OMN: "Omni Energy Ltd",
    OPA: "Opal Gas Limited",
    OPS: "Opus Energy Limited",
    OGS: "Opus Gas Supply Limited",
    ORB: "Orbit Energy Limited",
    SGD: "ORSTED SALES (UK) LIMITED",
    OSO: "Osso Gas Ltd",
    LUM: "Ovo Gas Limited",
    OVO: "OVO Gas Ltd",
    SPQ: "Ovo Gas Ltd",
    PLD: "Palladium Energy Supply Limited",
    PES: "People's Energy (Supply) Limited",
    PER: "Perle Energy Limited",
    PFE: "PFP Energy Supplies Limited",
    PZT: "Pozitive Energy Limited",
    TUP: "Pure Planet Limited",
    PUF: "PURF",
    RGN: "Regent Gas Limited",
    RIA: "Riadace Limited",
    RBH: "Robin Hood Energy Limited",
    RUT: "Rutherford Energy Supply Limited",
    NDL: "RWE Generation UK PLC",
    RST: "RWE Supply & Trading GmbH",
    ISR: "S.C. Isramart SRL",
    SCT: "Scottish Power Energy Retail Limited",
    SEE: "Shell Energy Europe Ltd",
    SHM: "Shell MGT Ltd",
    SID: "Simcoe Energy Limited",
    SPE: "Simplicity Energy Limited",
    SMT: "Smartest Energy Limited",
    SNO: "Snowdrop Energy Supply Ltd",
    STL: "So Energy Trading Limited",
    SES: "Social Energy Supply Limited",
    SOP: "Southern Electric Gas Limited",
    STH: "Southern Electric Gas Limited",
    ALA: "Square 1 Energy Limited",
    ATL: "SSE Energy Supply Limited",
    SHH: "SSE Energy Supply Limited",
    TRM: "Switch Business Gas and Power Ltd",
    SYM: "Symbio Energy Limited",
    TEL: "Telecom Plus Plc",
    TEM: "Temple Energy Limited",
    EUB: "The Energy Support Bureau LTD",
    REC: "The Renewable Energy Company",
    RSU: "The Royal Bank of Scotland",
    TIL: "Tillicum Energy Limited",
    AZA: "Together Energy Supply Ltd",
    TOB: "Tonik Energy Limited",
    PIL: "Tonik Energy Limited",
    TES: "Total Energy Gas Supplies Limited",
    AAS: "Total Gas & Power Limited",
    AGA: "Total Gas & Power Limited",
    EFG: "Total Gas and Power Ltd",
    TOE: "Toto Energy Limited",
    HDL: "Tru Energy Limited",
    UKG: "UK Gas Supply Ltd",
    UHC: "UK Healthcare Corporation Limited",
    BNG: "UK National Gas Ltd",
    UGP: "United Gas & Power Ltd",
    UEL: "Utilita Energy Limited",
    UGL: "Utilita Gas Limited",
    UTL: "Utility Point Limited",
    UTT: "Uttily PLC",
    SLD: "Valda Energy Limited",
    VAV: "VAVU Power Limited",
    VYU: "Naturgy Limited",
    NEO: "Neon Reef Limited",
    VIC: "Victory Energy Supply Limited",
    WMT: "Willamette",
    WIG: "WINGAS GmbH",
    XCL: "XCEL",
    BOR: "Zebra Power Limited",
    ZOG: "Zog Energy",
    ZYT: "Zythos Energy Limited",
    IDK: "I don’t know my supplier",
    MXE: "(The) Nuclear Decommissiong Authority"
  }
  
  export default data_gas_supplier_name;