// Images
import BGAS_logo from '../../../assets/img/suppliers/brisith-gas-logo.png';
import EDF_logo from '../../../assets/img/suppliers/edf-logo.svg';
import EON_logo from '../../../assets/img/suppliers/eon-logo.png';
import SSE_logo from '../../../assets/img/suppliers/sse-logo.svg';
import Scottish_logo from '../../../assets/img/suppliers/scottish-logo.png';
import Npower_logo from '../../../assets/img/suppliers/npower-logo.svg';


// Tariffs names
const data_electricity_tariffs_es = {
    "tariffs": [
        {
            "tariff_id": "EDF_12345_ES",
            "tariff_name": "EDF Standard",
            "unit_rate": 16.37,
            "standing_charge": 15.824,
            "monthly_cost": 42,
            "annual_cost": 504,
            "unitRateLimit": 300,
            "unit_rate_2": 9.69,
            "unit_rate_economy_7": 11.26,
            "exit_fees": 30,
            "supplier_img": EDF_logo,
            "fixed_period": 9,
            "review_rating": 5,
            "supplier_code": "EDF",
            "supplier_name": "EDF Energy"
        },
        {
            "tariff_id": "EDF_23416_ES",
            "tariff_name": "EDF Standard Variable",
            "svt": true,
            "unit_rate": 22,
            "standing_charge": 22,
            "monthly_cost": 22,
            "annual_cost": 504,
            "unitRateLimit": 22,
            "unit_rate_2": 22,
            "unit_rate_economy_7": 22,
            "exit_fees": 22,
            "supplier_img": EDF_logo,
            "fixed_period": 16,
            "review_rating": 5,
            "supplier_code": "EDF",
            "supplier_name": "EDF Energy"
        },
        {
            "tariff_id": "EDF_23417_ES",
            "tariff_name": "EDF Temporary May 2021",
            "unit_rate": 13.45,
            "standing_charge": 13.45,
            "monthly_cost": 13.45,
            "annual_cost": 504,
            "unitRateLimit": 13.45,
            "unit_rate_2": 13.45,
            "unit_rate_economy_7": 13.45,
            "exit_fees": 13.45,
            "supplier_img": EDF_logo,
            "fixed_period": 16,
            "review_rating": 5,
            "supplier_code": "EDF",
            "supplier_name": "EDF Energy"
        },
        {
            "tariff_id": "EDF_23418_ES",
            "tariff_name": "EDF HomeEnergy Fix April 2021",
            "unit_rate": 15.45,
            "standing_charge": 15.45,
            "monthly_cost": 15.45,
            "annual_cost": 146.76,
            "unitRateLimit": 15.45,
            "unit_rate_2": 15.45,
            "unit_rate_economy_7": 15.45,
            "exit_fees": 15.45,
            "supplier_img": EDF_logo,
            "fixed_period": 16,
            "review_rating": 5,
            "supplier_code": "EDF",
            "supplier_name": "EDF Energy"
        },
        {
            "tariff_id": "EDF_23419_ES",
            "tariff_name": "EDF Warm Home",
            "unit_rate": 16.42,
            "standing_charge": 16.42,
            "monthly_cost": 16.42,
            "annual_cost": 504,
            "unitRateLimit": 16.42,
            "unit_rate_2": 16.42,
            "unit_rate_economy_7": 16.42,
            "exit_fees": 16.42,
            "supplier_img": EDF_logo,
            "fixed_period": 16,
            "review_rating": 5,
            "supplier_code": "EDF",
            "supplier_name": "EDF Energy"
        },
        {
            "tariff_id": "EDF_23420_ES",
            "tariff_name": "EDF Economy 7",
            "unit_rate": 12.23,
            "standing_charge": 12.23,
            "monthly_cost": 12.23,
            "annual_cost": 146.76,
            "unitRateLimit": 12.23,
            "unit_rate_2": 12.23,
            "unit_rate_economy_7": 12.23,
            "exit_fees": 12.23,
            "supplier_img": EDF_logo,
            "fixed_period": 16,
            "review_rating": 5,
            "supplier_code": "EDF",
            "supplier_name": "EDF Energy"
        },
        {
            "tariff_id": "BRG_54432_ES",
            "tariff_name": "British Gas Standard",
            "unit_rate": 17,
            "standing_charge": 17,
            "monthly_cost": 17,
            "annual_cost": 204,
            "unitRateLimit": 17,
            "unit_rate_2": 17,
            "unit_rate_economy_7": 17,
            "exit_fees": 17,
            "supplier_img": BGAS_logo,
            "fixed_period": 8,
            "review_rating": 4,
            "supplier_code": "BRG",
            "supplier_name": "British Gas"
        },
        {
            "tariff_id": "BRG_54433_ES",
            "tariff_name": "British Gas Standard Variable",
            "svt": true,
            "unit_rate": 18.23,
            "standing_charge": 18.23,
            "monthly_cost": 18.23,
            "annual_cost": 204,
            "unitRateLimit": 18.23,
            "unit_rate_2": 18.23,
            "unit_rate_economy_7": 18.23,
            "exit_fees": 18.23,
            "supplier_img": BGAS_logo,
            "fixed_period": 8,
            "review_rating": 4,
            "supplier_code": "BRG",
            "supplier_name": "British Gas"
        },
        {
            "tariff_id": "BRG_54434_ES",
            "tariff_name": "British Gas Temporary May 2021",
            "unit_rate": 19.23,
            "standing_charge": 19.23,
            "monthly_cost": 19.23,
            "annual_cost": 204,
            "unitRateLimit": 19.23,
            "unit_rate_2": 19.23,
            "unit_rate_economy_7": 19.23,
            "exit_fees": 19.23,
            "supplier_img": BGAS_logo,
            "fixed_period": 8,
            "review_rating": 4,
            "supplier_code": "BRG",
            "supplier_name": "British Gas"
        },
        {
            "tariff_id": "BRG_54435_ES",
            "tariff_name": "British Gas HomeEnergy Fix April",
            "unit_rate": 19.68,
            "standing_charge": 19.68,
            "monthly_cost": 19.68,
            "annual_cost": 204,
            "unitRateLimit": 19.68,
            "unit_rate_2": 19.68,
            "unit_rate_economy_7": 19.68,
            "exit_fees": 19.68,
            "supplier_img": BGAS_logo,
            "fixed_period": 8,
            "review_rating": 4,
            "supplier_code": "BRG",
            "supplier_name": "British Gas"
        },
        {
            "tariff_id": "BRG_54436_ES",
            "tariff_name": "British Gas Warm Home",
            "unit_rate": 20,
            "standing_charge": 20,
            "monthly_cost": 20,
            "annual_cost": 204,
            "unitRateLimit": 20,
            "unit_rate_2": 20,
            "unit_rate_economy_7": 20,
            "exit_fees": 20,
            "supplier_img": BGAS_logo,
            "fixed_period": 8,
            "review_rating": 4,
            "supplier_code": "BRG",
            "supplier_name": "British Gas"
        },
        {
            "tariff_id": "BRG_54437_ES",
            "tariff_name": "British Gas Economy 7",
            "unit_rate": 20.58,
            "standing_charge": 20.58,
            "monthly_cost": 20.58,
            "annual_cost": 20.584,
            "unitRateLimit": 20.58,
            "unit_rate_2": 20.58,
            "unit_rate_economy_7": 20.58,
            "exit_fees": 20.58,
            "supplier_img": BGAS_logo,
            "fixed_period": 8,
            "review_rating": 4,
            "supplier_code": "BRG",
            "supplier_name": "British Gas"
        },
        {
            "tariff_id": "EON_23412_ES",
            "tariff_name": "EON Standard",
            "unit_rate": 18,
            "standing_charge": 18,
            "monthly_cost": 18,
            "annual_cost": 206,
            "unitRateLimit": 18,
            "unit_rate_2": 18,
            "unit_rate_economy_7": 18,
            "exit_fees": 18,
            "supplier_img": EON_logo,
            "fixed_period": 9,
            "review_rating": 4.5,
            "supplier_code": "EON",
            "supplier_name": "EON Energy"
        },
        {
            "tariff_id": "EON_23413_ES",
            "tariff_name": "EON Standar Variable",
            "unit_rate": 18.78,
            "standing_charge": 18.78,
            "monthly_cost": 18.78,
            "annual_cost": 206,
            "unitRateLimit": 18.78,
            "unit_rate_2": 18.78,
            "unit_rate_economy_7": 18.78,
            "exit_fees": 18.78,
            "supplier_img": EON_logo,
            "fixed_period": 9,
            "review_rating": 4.5,
            "supplier_code": "EON",
            "supplier_name": "EON Energy"
        },
        {
            "tariff_id": "EON_23414_ES",
            "tariff_name": "EON Temporary May 2021",
            "unit_rate": 19.28,
            "standing_charge": 19.28,
            "monthly_cost": 19.28,
            "annual_cost": 206,
            "unitRateLimit": 19.28,
            "unit_rate_2": 19.28,
            "unit_rate_economy_7": 19.28,
            "exit_fees": 19.28,
            "supplier_img": EON_logo,
            "fixed_period": 9,
            "review_rating": 4.5,
            "supplier_code": "EON",
            "supplier_name": "EON Energy"
        },
        {
            "tariff_id": "EON_23415_ES",
            "tariff_name": "EON HomeEnergy Fix April",
            "unit_rate": 17.28,
            "standing_charge": 17.28,
            "monthly_cost": 17.28,
            "annual_cost": 206,
            "unitRateLimit": 17.28,
            "unit_rate_2": 17.28,
            "unit_rate_economy_7": 17.28,
            "exit_fees": 17.28,
            "supplier_img": EON_logo,
            "fixed_period": 9,
            "review_rating": 4.5,
            "supplier_code": "EON",
            "supplier_name": "EON Energy"
        },
        {
            "tariff_id": "EON_23416_ES",
            "tariff_name": "EON Warm Home",
            "unit_rate": 16.28,
            "standing_charge": 16.28,
            "monthly_cost": 16.28,
            "annual_cost": 206,
            "unitRateLimit": 16.28,
            "unit_rate_2": 16.28,
            "unit_rate_economy_7": 16.28,
            "exit_fees": 16.28,
            "supplier_img": EON_logo,
            "fixed_period": 9,
            "review_rating": 4.5,
            "supplier_code": "EON",
            "supplier_name": "EON Energy"
        },
        {
            "tariff_id": "EON_23417_ES",
            "tariff_name": "EON Economy 7",
            "unit_rate": 19,
            "standing_charge": 19,
            "monthly_cost": 19,
            "annual_cost": 206,
            "unitRateLimit": 19,
            "unit_rate_2": 19,
            "unit_rate_economy_7": 19,
            "exit_fees": 19,
            "supplier_img": EON_logo,
            "fixed_period": 9,
            "review_rating": 4.5,
            "supplier_code": "EON",
            "supplier_name": "EON Energy"
        },
        {
            "tariff_id": "SSE_23413_ES",
            "tariff_name": "SSE Standard",
            "unit_rate": 19,
            "standing_charge": 19,
            "monthly_cost": 19,
            "annual_cost": 300,
            "unitRateLimit": 19,
            "unit_rate_2": 19,
            "unit_rate_economy_7": 19,
            "exit_fees": 19,
            "supplier_img": SSE_logo,
            "fixed_period": 10,
            "review_rating": 5,
            "supplier_code": "SSE",
            "supplier_name": "SSE"
        },
        {
            "tariff_id": "SSE_23414_ES",
            "tariff_name": "SSE Standard Variable",
            "svt": true,
            "unit_rate": 19.33,
            "standing_charge": 19.33,
            "monthly_cost": 19.33,
            "annual_cost": 300,
            "unitRateLimit": 19.33,
            "unit_rate_2": 19.33,
            "unit_rate_economy_7": 19.33,
            "exit_fees": 19.33,
            "supplier_img": SSE_logo,
            "fixed_period": 10,
            "review_rating": 5,
            "supplier_code": "SSE",
            "supplier_name": "SSE"
        },
        {
            "tariff_id": "SSE_23415_ES",
            "tariff_name": "SSE Temporary May 2021",
            "unit_rate": 20,
            "standing_charge": 20,
            "monthly_cost": 20,
            "annual_cost": 300,
            "unitRateLimit": 20,
            "unit_rate_2": 20,
            "unit_rate_economy_7": 20,
            "exit_fees": 20,
            "supplier_img": SSE_logo,
            "fixed_period": 10,
            "review_rating": 5,
            "supplier_code": "SSE",
            "supplier_name": "SSE"
        },
        {
            "tariff_id": "SSE_23416_ES",
            "tariff_name": "SSE HomeEnergy Fix April",
            "unit_rate": 20.47,
            "standing_charge": 20.47,
            "monthly_cost": 20.47,
            "annual_cost": 300,
            "unitRateLimit": 20.47,
            "unit_rate_2": 20.47,
            "unit_rate_economy_7": 20.47,
            "exit_fees": 20.47,
            "supplier_img": SSE_logo,
            "fixed_period": 10,
            "review_rating": 5,
            "supplier_code": "SSE",
            "supplier_name": "SSE"
        },
        {
            "tariff_id": "SSE_23417_ES",
            "tariff_name": "SSE Warm Home",
            "unit_rate": 16.13,
            "standing_charge": 16.13,
            "monthly_cost": 16.13,
            "annual_cost": 300,
            "unitRateLimit": 16.13,
            "unit_rate_2": 16.13,
            "unit_rate_economy_7": 16.13,
            "exit_fees": 16.13,
            "supplier_img": SSE_logo,
            "fixed_period": 10,
            "review_rating": 5,
            "supplier_code": "SSE",
            "supplier_name": "SSE"
        },
        {
            "tariff_id": "SSE_23418_ES",
            "tariff_name": "SSE Economy 7",
            "unit_rate": 18.13,
            "standing_charge": 18.13,
            "monthly_cost": 18.13,
            "annual_cost": 300,
            "unitRateLimit": 18.13,
            "unit_rate_2": 18.13,
            "unit_rate_economy_7": 18.13,
            "exit_fees": 18.13,
            "supplier_img": SSE_logo,
            "fixed_period": 10,
            "review_rating": 5,
            "supplier_code": "SSE",
            "supplier_name": "SSE"
        },
        {
            "tariff_id": "SCO_23414_ES",
            "tariff_name": "Scottish Standard",
            "unit_rate": 20,
            "standing_charge": 20,
            "monthly_cost": 240,
            "annual_cost": 504,
            "unitRateLimit": 20,
            "unit_rate_2": 20,
            "unit_rate_economy_7": 20,
            "exit_fees": 20,
            "supplier_img": Scottish_logo,
            "fixed_period": 16,
            "review_rating": 4.5,
            "supplier_code": "SCO",
            "supplier_name": "Scottish Power"
        },
        {
            "tariff_id": "SCO_23415_ES",
            "tariff_name": "Scottish Power Standard Variable",
            "svt": true,
            "unit_rate": 20.50,
            "standing_charge": 20.50,
            "monthly_cost": 240,
            "annual_cost": 504,
            "unitRateLimit": 20.50,
            "unit_rate_2": 20.50,
            "unit_rate_economy_7": 20.50,
            "exit_fees": 20.50,
            "supplier_img": Scottish_logo,
            "fixed_period": 16,
            "review_rating": 4.5,
            "supplier_code": "SCO",
            "supplier_name": "Scottish Power"
        },
        {
            "tariff_id": "SCO_23416_ES",
            "tariff_name": "Scottish Temporary May 2021",
            "unit_rate": 21.22,
            "standing_charge": 21.22,
            "monthly_cost": 240,
            "annual_cost": 504,
            "unitRateLimit": 21.22,
            "unit_rate_2": 21.22,
            "unit_rate_economy_7": 21.22,
            "exit_fees": 21.22,
            "supplier_img": Scottish_logo,
            "fixed_period": 16,
            "review_rating": 4.5,
            "supplier_code": "SCO",
            "supplier_name": "Scottish Power"
        },
        {
            "tariff_id": "SCO_23417_ES",
            "tariff_name": "Scottish HomeEnergy Fix April",
            "unit_rate": 22,
            "standing_charge": 22,
            "monthly_cost": 240,
            "annual_cost": 504,
            "unitRateLimit": 22,
            "unit_rate_2": 22,
            "unit_rate_economy_7": 22,
            "exit_fees": 22,
            "supplier_img": Scottish_logo,
            "fixed_period": 16,
            "review_rating": 4.5,
            "supplier_code": "SCO",
            "supplier_name": "Scottish Power"
        },
        {
            "tariff_id": "SCO_23418_ES",
            "tariff_name": "Scottish Warm Home",
            "unit_rate": 17.54,
            "standing_charge": 17.54,
            "monthly_cost": 240,
            "annual_cost": 504,
            "unitRateLimit": 17.54,
            "unit_rate_2": 17.54,
            "unit_rate_economy_7": 17.54,
            "exit_fees": 17.54,
            "supplier_img": Scottish_logo,
            "fixed_period": 16,
            "review_rating": 4.5,
            "supplier_code": "SCO",
            "supplier_name": "Scottish Power"
        },
        {
            "tariff_id": "SCO_23419_ES",
            "tariff_name": "Scottish Economy 7",
            "unit_rate": 19.54,
            "standing_charge": 19.54,
            "monthly_cost": 240,
            "annual_cost": 504,
            "unitRateLimit": 19.54,
            "unit_rate_2": 19.54,
            "unit_rate_economy_7": 19.54,
            "exit_fees": 19.54,
            "supplier_img": Scottish_logo,
            "fixed_period": 16,
            "review_rating": 4.5,
            "supplier_code": "SCO",
            "supplier_name": "Scottish Power"
        },
        {
            "tariff_id": "NPO_23415_ES",
            "tariff_name": "NPOWER Standard",
            "unit_rate": 21,
            "standing_charge": 21,
            "monthly_cost": 21,
            "annual_cost": 250,
            "unitRateLimit": 21,
            "unit_rate_2": 21,
            "unit_rate_economy_7": 21,
            "exit_fees": 21,
            "supplier_img": Npower_logo,
            "fixed_period": 24,
            "review_rating": 4,
            "supplier_code": "NPO",
            "supplier_name": "NPOWER"
        },
        {
            "tariff_id": "NPO_23416_ES",
            "tariff_name": "NPOWER Standard Variable",
            "svt": true,
            "unit_rate": 21.52,
            "standing_charge": 21.52,
            "monthly_cost": 21.52,
            "annual_cost": 250,
            "unitRateLimit": 21.52,
            "unit_rate_2": 21.52,
            "unit_rate_economy_7": 21.52,
            "exit_fees": 21.52,
            "supplier_img": Npower_logo,
            "fixed_period": 24,
            "review_rating": 4,
            "supplier_code": "NPO",
            "supplier_name": "NPOWER"
        },
        {
            "tariff_id": "NPO_23417_ES",
            "tariff_name": "NPOWER Temporary May 2021",
            "unit_rate": 23,
            "standing_charge": 23,
            "monthly_cost": 23,
            "annual_cost": 250,
            "unitRateLimit": 23,
            "unit_rate_2": 23,
            "unit_rate_economy_7": 23,
            "exit_fees": 23,
            "supplier_img": Npower_logo,
            "fixed_period": 24,
            "review_rating": 4,
            "supplier_code": "NPO",
            "supplier_name": "NPOWER"
        },
        {
            "tariff_id": "NPO_23418_ES",
            "tariff_name": "NPOWER HomeEnergy Fix April",
            "unit_rate": 14.11,
            "standing_charge": 14.11,
            "monthly_cost": 14.11,
            "annual_cost": 250,
            "unitRateLimit": 14.11,
            "unit_rate_2": 14.11,
            "unit_rate_economy_7": 14.11,
            "exit_fees": 14.11,
            "supplier_img": Npower_logo,
            "fixed_period": 24,
            "review_rating": 4,
            "supplier_code": "NPO",
            "supplier_name": "NPOWER"
        },
        {
            "tariff_id": "NPO_23419_ES",
            "tariff_name": "NPOWER Warm Home",
            "unit_rate": 15.11,
            "standing_charge": 15.11,
            "monthly_cost": 15.11,
            "annual_cost": 250,
            "unitRateLimit": 15.11,
            "unit_rate_2": 15.11,
            "unit_rate_economy_7": 15.11,
            "exit_fees": 15.11,
            "supplier_img": Npower_logo,
            "fixed_period": 24,
            "review_rating": 4,
            "supplier_code": "NPO",
            "supplier_name": "NPOWER"
        },
        {
            "tariff_id": "NPO_23420_ES",
            "tariff_name": "GREEN ENERGY",
            "unit_rate": 13.23,
            "standing_charge": 13.23,
            "monthly_cost": 13.23,
            "annual_cost": 250,
            "unitRateLimit": 13.23,
            "unit_rate_2": 13.23,
            "unit_rate_economy_7": 13.23,
            "exit_fees": 13.23,
            "supplier_img": Npower_logo,
            "fixed_period": 24,
            "review_rating": 4,
            "supplier_code": "NPO",
            "supplier_name": "NPOWER"
        }
    ]
};

export default data_electricity_tariffs_es;